inherit_from:
 - .rubocop_airbnb.yml
# Rails用に最適化
Rails:
  Enabled: true

#missing top-level class documentation commentの除外追加
Documentation:
  Enabled: false

AllCops:
  NewCops: enable

# 文字数の上限を８０文字から変更
LineLength:
  Max: 160

#rubocopで検証したくないフォルダを指定
AllCops:
  Exclude:
    - 'db/**/*'
    - 'db/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/apprication.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/spec_helper.rb'
