version: "3"

services:
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: app_app
    ports:
      - '3000:3000'
    env_file:
      - ./environments/db.env
    depends_on:
      - db
    networks:
      - default
    command: bundle exec rails server -b 0.0.0.0
